### PR TITLE
clarify a readme note on usage

### PR DESCRIPTION
**Pull request by capaj**
it is confusing to say that you can polyfill proxies

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
You can polyfill proxies, they just won't match the behaviour exactly

**Comment by capaj** [comment]
Let me ask this way-does your test suite pass with a Proxy polyfill? It should not be hard to run it with a monkey patched Proxy. If it does then it makes sense to have it there. If not it would probably be better to merge this.

**Comment by ForsakenHarmony** [comment]
I could try that actually, the main thing the polyfill does not support is properties added later on

**Comment by ForsakenHarmony** [comment]
bors try

**Comment by ForsakenHarmony** [comment]
never got around to it so I'm just gonna merge this

**Pull request merged**
